global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'spring-boot-app'
    metrics_path: '/task-manager/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']
