spring:
  profiles:
    active: dev
  cache:
    type: caffeine
    caffeine:
      maximum-size: 5000
      expire-after-write: 600

server:
  port: 8080
  servlet:
    context-path: /task-manager

api:
  base:
    url: /api/v1

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
  default-produces-media-type: application/json
  show-login-endpoint: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  info:
    env:
      enabled: true

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.cache: DEBUG

crypto:
  cipher-algorithm: ${CRYPTO_CIPHER_ALGORITHM}
  keys:
    AES: ${CRYPTO_KEYS_AES}

hash:
  algorithm: ${HASH_ALGORITHM}

admin:
  username: ${ADMIN_USERNAME}
  first-name: ${ADMIN_FIRST_NAME}
  last-name: ${ADMIN_LAST_NAME}
  email: ${ADMIN_EMAIL}
  password: ${ADMIN_PASSWORD}
  birth-date: ${ADMIN_BIRTH_DATE}
  phone-number: ${ADMIN_PHONE_NUMBER}
