spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/taskmanagerdb
    username: your_username
    password: your_secure_password
    hikari:
      initialization-fail-timeout: 5000
      schema: taskmanager
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    user: your_username
    password: your_secure_password
  docker:
    compose:
      enabled: true
      file: docker-compose.yaml
