spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/taskmanagerdb
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    hikari:
      initialization-fail-timeout: 5000
      schema: taskmanager
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  docker:
    compose:
      enabled: true
      file: docker-compose.yaml

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}
  issuer: ${JWT_ISSUER}
