spring:
  profiles:
    active: dev
  cache:
    type: caffeine
    caffeine:
      maximum-size: 5000
      expire-after-write: 600

server:
  port: 8080
  servlet:
    context-path: /task-manager

api:
  base:
    url: /api/v1

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
  default-produces-media-type: application/json
  show-login-endpoint: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  info:
    env:
      enabled: true

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.cache: DEBUG

crypto:
  cipher-algorithm: AES/ECB/PKCS5Padding
  keys:
    AES: 770A8A65DA156D24EE2A093277530142

hash:
  algorithm: HmacSHA256

admin:
  username: admin
  first-name: admin
  last-name: admin
  email: admin@effectmobile.ru
  password: YourPassword123!
  birth-date: 1995-03-05
  phone-number: +71234567890

jwt:
  secret: bXlTdXBlclNlY3JldEtleTEyMzQ1Njc4OTAwNTAzMTk5NUF6ZXJiYWlqYW4
  expiration: 86400000
  issuer: task-management-system